# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0497e46502640e6a97c8e82ee3508bc717dfdd398802ce407bd3f854a8ed0f8cc11bc87cd60e265c9fa2ba4fdceb5210dfca2681cc888b84bfad332a314053ec

test:
  secret_key_base: c0dc2dfa42c9427d4a5cdfeaedaa5a4a15ea0b759020c062a7572d0624052da394a41b751242e6af5c6c8784118f82324610ff828c95acf6ff5aef9dadfeb035

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
